openapi: 3.0.3
info:
  title: Cryptocurrency Recommendation API
  description: There are 3 APIs exposed all reading from the csv files of given cryptocurrencies. The APIs retrieve data from those cryptocurrencies
  version: 1.0.0
paths:
  /v1/all-sorted:
    $ref: 'crypto-recommendation-paths.yaml#/operations/crypto-sorted-descending-operation'
  /v1/{cryptoSymbol}/info:
    $ref: 'crypto-recommendation-paths.yaml#/operations/crypto-info-operation'
  /v1/highest-range:
    $ref: 'crypto-recommendation-paths.yaml#/operations/highest-range-operation'
  /v1/by-market-status:
    $ref: 'crypto-recommendation-paths.yaml#/operations/by-market-status-operation'
